[2022-07-16 12:38:29,113] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: car_price_prediction.pipeline manual__2022-07-16T12:38:24.115312+00:00 [queued]>
[2022-07-16 12:38:29,138] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: car_price_prediction.pipeline manual__2022-07-16T12:38:24.115312+00:00 [queued]>
[2022-07-16 12:38:29,152] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-16 12:38:29,156] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-07-16 12:38:29,158] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-16 12:38:29,279] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): pipeline> on 2022-07-16 12:38:24.115312+00:00
[2022-07-16 12:38:29,297] {standard_task_runner.py:52} INFO - Started process 3010 to run task
[2022-07-16 12:38:29,308] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'car_price_prediction', 'pipeline', 'manual__2022-07-16T12:38:24.115312+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/hw_dag.py', '--cfg-path', '/tmp/tmpkxcozta3', '--error-file', '/tmp/tmpr6_5no0n']
[2022-07-16 12:38:29,319] {standard_task_runner.py:80} INFO - Job 51: Subtask pipeline
[2022-07-16 12:38:29,654] {task_command.py:371} INFO - Running <TaskInstance: car_price_prediction.pipeline manual__2022-07-16T12:38:24.115312+00:00 [running]> on host 744d078d7eff
[2022-07-16 12:38:30,026] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=car_price_prediction
AIRFLOW_CTX_TASK_ID=pipeline
AIRFLOW_CTX_EXECUTION_DATE=2022-07-16T12:38:24.115312+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-16T12:38:24.115312+00:00
[2022-07-16 12:38:36,859] {pipeline.py:116} INFO - model: LogisticRegression, acc_mean: 0.7591, acc_std: 0.0075
[2022-07-16 12:39:33,230] {pipeline.py:116} INFO - model: RandomForestClassifier, acc_mean: 0.7763, acc_std: 0.0057
[2022-07-16 12:40:26,944] {pipeline.py:116} INFO - model: SVC, acc_mean: 0.7871, acc_std: 0.0042
[2022-07-16 12:40:26,948] {pipeline.py:121} INFO - best model: SVC, accuracy: 0.7871
[2022-07-16 12:40:46,163] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/modules/pipeline.py", line 126, in pipeline
    with open(model_filename, 'wb') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/models/cars_pipe_202207161240.pkl'
[2022-07-16 12:40:46,184] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=car_price_prediction, task_id=pipeline, execution_date=20220716T123824, start_date=20220716T123829, end_date=20220716T124046
[2022-07-16 12:40:46,208] {standard_task_runner.py:97} ERROR - Failed to execute job 51 for task pipeline ([Errno 2] No such file or directory: '/opt/airflow/data/models/cars_pipe_202207161240.pkl'; 3010)
[2022-07-16 12:40:46,295] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-16 12:40:46,366] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
