[2022-07-15 15:17:06,300] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: car_price_prediction.pipeline manual__2022-07-15T15:15:54.530272+00:00 [queued]>
[2022-07-15 15:17:06,320] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: car_price_prediction.pipeline manual__2022-07-15T15:15:54.530272+00:00 [queued]>
[2022-07-15 15:17:06,324] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-15 15:17:06,325] {taskinstance.py:1377} INFO - Starting attempt 2 of 2
[2022-07-15 15:17:06,327] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-15 15:17:06,356] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): pipeline> on 2022-07-15 15:15:54.530272+00:00
[2022-07-15 15:17:06,370] {standard_task_runner.py:52} INFO - Started process 1970 to run task
[2022-07-15 15:17:06,377] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'car_price_prediction', 'pipeline', 'manual__2022-07-15T15:15:54.530272+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/hw_dag.py', '--cfg-path', '/tmp/tmp_3qqaow9', '--error-file', '/tmp/tmp9f3k3w72']
[2022-07-15 15:17:06,380] {standard_task_runner.py:80} INFO - Job 46: Subtask pipeline
[2022-07-15 15:17:06,711] {task_command.py:371} INFO - Running <TaskInstance: car_price_prediction.pipeline manual__2022-07-15T15:15:54.530272+00:00 [running]> on host 744d078d7eff
[2022-07-15 15:17:07,063] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=car_price_prediction
AIRFLOW_CTX_TASK_ID=pipeline
AIRFLOW_CTX_EXECUTION_DATE=2022-07-15T15:15:54.530272+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-15T15:15:54.530272+00:00
[2022-07-15 15:17:07,070] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/modules/pipeline.py", line 70, in pipeline
    df = pd.read_csv(f'{path}/dags/data/train/homework.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/Users/yuliv/airflow/airflow_hw/dags/data/train/homework.csv'
[2022-07-15 15:17:07,114] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=car_price_prediction, task_id=pipeline, execution_date=20220715T151554, start_date=20220715T151706, end_date=20220715T151707
[2022-07-15 15:17:07,158] {standard_task_runner.py:97} ERROR - Failed to execute job 46 for task pipeline ([Errno 2] No such file or directory: '/Users/yuliv/airflow/airflow_hw/dags/data/train/homework.csv'; 1970)
[2022-07-15 15:17:07,199] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-15 15:17:07,324] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
